# lwf 테스트
# dkd_m = 0.5 -> 돌아가는 중
## 100%KD
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1 --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch all --dkd-shape one --distill-percent 1 --ikr-control none
## 80%KD
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1 --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch cycle --dkd-shape one --distill-percent 0.8 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1 --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch first --dkd-shape one --distill-percent 0.8 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1 --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch mid --dkd-shape one --distill-percent 0.8 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch end --dkd-shape one --distill-percent 0.8 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch first_end --dkd-shape one --distill-percent 0.8 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch ten_to_ten --dkd-shape one --distill-percent 0.8 --ikr-control none
## 60%KD
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch cycle --dkd-shape one --distill-percent 0.6 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch first --dkd-shape one --distill-percent 0.6 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch mid --dkd-shape one --distill-percent 0.6 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch end --dkd-shape one --distill-percent 0.6 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch first_end --dkd-shape one --distill-percent 0.6 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch ten_to_ten --dkd-shape one --distill-percent 0.6 --ikr-control none
## 40%KD
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch cycle --dkd-shape one --distill-percent 0.4 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch first --dkd-shape one --distill-percent 0.4 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch mid --dkd-shape one --distill-percent 0.4 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch end --dkd-shape one --distill-percent 0.4 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch first_end --dkd-shape one --distill-percent 0.4 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch ten_to_ten --dkd-shape one --distill-percent 0.4 --ikr-control none
## 20%KD
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch cycle --dkd-shape one --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch first --dkd-shape one --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch mid --dkd-shape one --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch end --dkd-shape one --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch first_end --dkd-shape one --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_1  --eval-on-train --batch-size 128 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 0.5 --dkd-switch ten_to_ten --dkd-shape one --distill-percent 0.2 --ikr-control none
