# dkd_m = 0.5

## cycle
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch cycle --dkd-shape linear_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch cycle --dkd-shape linear_decrease --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch cycle --dkd-shape concaved_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch cycle --dkd-shape concaved_decrease --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch cycle --dkd-shape convexed_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch cycle --dkd-shape convexed_decrease --distill-percent 0.2 --ikr-control none

## first
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch first --dkd-shape linear_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch first --dkd-shape linear_decrease --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch first --dkd-shape concaved_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch first --dkd-shape concaved_decrease --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch first --dkd-shape convexed_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch first --dkd-shape convexed_decrease --distill-percent 0.2 --ikr-control none

## mid
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch mid --dkd-shape linear_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch mid --dkd-shape linear_decrease --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch mid --dkd-shape concaved_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch mid --dkd-shape concaved_decrease --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch mid --dkd-shape convexed_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch mid --dkd-shape convexed_decrease --distill-percent 0.2 --ikr-control none

## end
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch end --dkd-shape linear_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch end --dkd-shape linear_decrease --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch end --dkd-shape concaved_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch end --dkd-shape concaved_decrease --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch end --dkd-shape convexed_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch end --dkd-shape convexed_decrease --distill-percent 0.2 --ikr-control none


## first_end
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch first_end --dkd-shape linear_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch first_end --dkd-shape linear_decrease --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch first_end --dkd-shape concaved_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch first_end --dkd-shape concaved_decrease --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch first_end --dkd-shape convexed_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch first_end --dkd-shape convexed_decrease --distill-percent 0.2 --ikr-control none

## ten_to_ten
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch ten_to_ten --dkd-shape linear_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch ten_to_ten --dkd-shape linear_decrease --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch ten_to_ten --dkd-shape concaved_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch ten_to_ten --dkd-shape concaved_decrease --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch ten_to_ten --dkd-shape convexed_increase --distill-percent 0.2 --ikr-control none
python3 -u src/main_incremental.py --gpu 0 --results-path exp1_2 --eval-on-train --batch-size 128 --wandb-project exp1_2_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 0.5 --dkd-switch ten_to_ten --dkd-shape convexed_decrease --distill-percent 0.2 --ikr-control none

