# python3 -u src/main_incremental.py --gpu 0 --dataset imagenet_32_reduced --results-path exp1_1 --eval-on-train --batch-size 512 --wandb-project exp1_1_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 2.0 --dkd-switch ten_to_ten --dkd-shape one --distill-percent 0.2 --ikr-control none

# python3 -u src/main_incremental.py --gpu 0 --dataset imagenet_32_reduced --results-path exp1_1 --eval-on-train --batch-size 512 --wandb-project exp1_1_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 1.0 --dkd-switch all --dkd-shape one --distill-percent 1 --ikr-control none

# python3 -u src/main_incremental.py --gpu 0 --dataset cifar100 --results-path exp1_1 --network resnet32_ --eval-on-train --batch-size 512 --wandb-project exp1_1_icarl --nepoch 200 --approach icarl --dkd-control deterministic --dkd-m 1.0 --dkd-switch all --dkd-shape one --distill-percent 1 --ikr-control none

# python3 -u src/main_incremental.py --gpu 0 --dataset imagenet_32_reduced --results-path exp1_1 --network resnet32 --eval-on-train --batch-size 512 --wandb-project exp1_1_lwf --nepoch 200 --approach lwf --dkd-control deterministic --dkd-m 1.0 --dkd-switch all --dkd-shape one --distill-percent 1 --ikr-control none
# python3 -u src/main_incremental.py --gpu 0 --dataset imagenet_32_reduced --results-path exp1_1 --network resnet32 --eval-on-train --batch-size 512 --wandb-project exp1_1_1_lucir --nepoch 200 --approach lucir --dkd-control deterministic --dkd-m 1.0 --dkd-switch all --dkd-shape one --distill-percent 1 --ikr-control none
# python3 -u src/main_incremental.py --gpu 0 --dataset imagenet_32_reduced --results-path exp1_1 --network resnet32 --eval-on-train --batch-size 512 --wandb-project exp1_1_lwm --nepoch 200 --approach lwm --dkd-control deterministic --dkd-m 1.0 --dkd-switch all --dkd-shape one --distill-percent 1 --ikr-control none
